// A curated list of short, common, easy-to-type English words used to build
// high-entropy passphrases (Diceware-style). Kept free of ambiguous or
// hard-to-spell entries so generated passphrases stay memorable.
export const WORDLIST = [
  'anchor', 'ankle', 'apple', 'arrow', 'ashen', 'atlas', 'aunt', 'autumn',
  'badge', 'bakery', 'balloon', 'bamboo', 'banjo', 'basket', 'beacon', 'beaver',
  'bicycle', 'birch', 'bison', 'blanket', 'blossom', 'boulder', 'bramble', 'breeze',
  'bridge', 'bucket', 'bugle', 'burrow', 'cabin', 'cactus', 'camel', 'candle',
  'canoe', 'canyon', 'carbon', 'carpet', 'cascade', 'castle', 'cedar', 'cellar',
  'chalk', 'charm', 'cherry', 'chimney', 'cinder', 'clover', 'coast', 'cobalt',
  'comet', 'compass', 'copper', 'coral', 'cotton', 'cousin', 'coyote', 'crater',
  'cricket', 'cruise', 'cymbal', 'dagger', 'daisy', 'dawn', 'delta', 'desert',
  'diamond', 'dolphin', 'domino', 'dragon', 'drift', 'drum', 'dusk', 'eagle',
  'echo', 'ember', 'emerald', 'engine', 'falcon', 'feather', 'fennel', 'ferry',
  'fiber', 'fiddle', 'field', 'finch', 'flame', 'flannel', 'flint', 'forest',
  'fossil', 'fountain', 'fox', 'frost', 'garden', 'garnet', 'gecko', 'ginger',
  'glacier', 'glove', 'goblet', 'granite', 'grove', 'gully', 'hamlet', 'harbor',
  'harvest', 'hazel', 'heron', 'hickory', 'holly', 'honey', 'hornet', 'hotel',
  'hunter', 'iguana', 'indigo', 'island', 'ivory', 'jacket', 'jade', 'jasmine',
  'jelly', 'jigsaw', 'juniper', 'kettle', 'kitten', 'kiwi', 'lagoon', 'lantern',
  'laurel', 'lemon', 'lentil', 'lilac', 'linen', 'lizard', 'lobster', 'locket',
  'lotus', 'lumber', 'lunar', 'lynx', 'magnet', 'maple', 'marble', 'marsh',
  'meadow', 'melon', 'mesa', 'meteor', 'mimosa', 'mint', 'mirror', 'mistral',
  'mitten', 'monarch', 'moose', 'moss', 'mountain', 'mustang', 'nectar', 'needle',
  'nickel', 'nimbus', 'noodle', 'nutmeg', 'oasis', 'oatmeal', 'ocean', 'ochre',
  'onyx', 'opal', 'orange', 'orbit', 'orchid', 'osprey', 'otter', 'oyster',
  'paddle', 'panda', 'pantry', 'parcel', 'parrot', 'pebble', 'pecan', 'penny',
  'pepper', 'petal', 'pigeon', 'pillow', 'pine', 'planet', 'plaza', 'pocket',
  'poplar', 'poppy', 'possum', 'prairie', 'pretzel', 'puddle', 'pumpkin', 'quartz',
  'quilt', 'rabbit', 'raccoon', 'rainbow', 'raisin', 'raven', 'reef', 'ribbon',
  'ridge', 'river', 'rocket', 'rooster', 'rosemary', 'saddle', 'saffron', 'salmon',
  'sandal', 'sapphire', 'satin', 'savory', 'scarf', 'sequoia', 'shadow', 'shamrock',
  'shell', 'shrimp', 'silver', 'sketch', 'skylark', 'sleet', 'sliver', 'sloth',
  'smoke', 'sonnet', 'sorrel', 'sparrow', 'sphinx', 'spiral', 'sponge', 'spruce',
  'squid', 'stable', 'stamp', 'starling', 'statue', 'stone', 'stork', 'stream',
  'sunset', 'swan', 'sycamore', 'tangerine', 'tempo', 'terrace', 'thimble', 'thistle',
  'thunder', 'timber', 'toffee', 'tortoise', 'trellis', 'trumpet', 'tulip', 'tundra',
  'turnip', 'turtle', 'tusk', 'umbrella', 'valley', 'velvet', 'vernal', 'violet',
  'volcano', 'walnut', 'walrus', 'warbler', 'wattle', 'whale', 'wharf', 'wicker',
  'widget', 'willow', 'window', 'winter', 'wolf', 'wren', 'yarrow', 'zebra',
  'zephyr', 'zinnia',
]
